# Generated by Django 5.1.2 on 2024-11-26 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.DateField(default=django.utils.timezone.now)),
                ('delivered_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_service', to='carwash.appointment')),
            ],
        ),
    ]
